[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["v4-core/=lib/v4-core/"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
solc_version = "0.8.26"
evm_version = "cancun"
via_ir = true
optimizer = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
